### PR TITLE
Todo_List Web App 

### PR DESCRIPTION
**Pull request by LawSibisi**
I am creating a todo list in order to keep track of the tasks I have during each day. Then I want to store the data on a DB.

My Project consists of HTML, CSS, JavaScript, Node modules, and node js server

**Add New Tasks:** 
Users can type a new task into an input field and add it to the list by clicking the "Add" button. Each task is stored in a MongoDB database.

**Edit Tasks:**
Users can click an "Edit" button beside each task to modify the task text. A modal window opens with the current task text pre-filled, allowing users to make changes and save them. The updated task text is sent to the backend for updating in the database.

**Mark Tasks as Completed**
Each task has a "Mark Complete" button, allowing users to toggle the completion status of a task. When a task is marked as complete, it appears with a distinct style. Users can also unmark a task if needed.

**Delete Tasks:**
Users can remove tasks from the list by clicking a close (×) button next to each task. After confirmation, the task is deleted from both the UI and the database.

**Backend Integration:** 
The project includes backend API endpoints for handling task-related operations like creating, updating, deleting, and toggling completion. These API calls are made using fetch requests from the frontend, enabling full CRUD (Create, Read, Update, Delete) functionality.

### CODE REVIEW

**Review by H3RT — CHANGES_REQUESTED** [review]
I see you've added files, please start with your index file.

**Review by H3RT — CHANGES_REQUESTED** [review]
I see that you've started with your index page. I also see that there is a piece of code that s commented out please remove it if you are not using it or un comment is . Also add an edit button to your list items.

**Review by H3RT — COMMENTED** [review]
I see the implemented changes, I feel like your code needs styling to it.

**Review by H3RT — COMMENTED** [review]
Please don't forget that you must add a edit button and that your todo list should mark as complete and should be able to delete. Please style that

**Review by LundiLanga — CHANGES_REQUESTED** [review]
Your front-end looks good. 

I believe you will be working on moving the edit textbox to the bottom of the add task textbox not putting it on the side.

**Review by H3RT — COMMENTED** [review]
Okay see you implemented the requested changes. Please add responsiveness to your code

**Review by H3RT — COMMENTED** [review]
Ensure that it's working and then you can start adding functionality

**Review by LundiLanga — CHANGES_REQUESTED** [review]
I see the changes you've made, please add javascript functionality because i don't see it in your js files.

**Review by Sinethemba7vitsha — APPROVED** [review]
Pretty happy with the code looks nice

**Review by LundiLanga — APPROVED** [review]
Everything seems to be functioning properly.

**Review by H3RT — APPROVED** [review]

**Pull request merged**
